spring:
    rabbitmq:
        host: localhost
        port: 5672
    multirabbitmq:
        connections:
            connectionName1:
                host: localhost
                port: 5673
            connectionName2:
                host: localhost
                port: 5674

    main:
        allow-bean-definition-overriding: true


